#!/usr/bin/env bash
#
# Generate Sources/GazeKit/FaceMeshTriangulation.swift from MediaPipe's
# canonical_face_model.obj (Apache License 2.0).
#
# The download is verified against the expected vertex and face counts before
# any output is written, the 1-based faces are converted to 0-based vertex
# triples, and the file is written in one move. Re-running the script produces
# a byte-identical file.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SOURCE_URL="https://raw.githubusercontent.com/google-ai-edge/mediapipe/master/mediapipe/modules/face_geometry/data/canonical_face_model.obj"
OUTPUT="Sources/GazeKit/FaceMeshTriangulation.swift"
VERTEX_COUNT=468
TRIANGLE_COUNT=898

SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/smart-gaze-triangulation.XXXXXX")"
trap 'rm -rf "$SCRATCH"' EXIT

echo "Downloading canonical_face_model.obj..."
curl --fail --location --silent --show-error --output "$SCRATCH/model.obj" "$SOURCE_URL"

vertex_count="$(grep -c '^v ' "$SCRATCH/model.obj" || true)"
face_count="$(grep -c '^f ' "$SCRATCH/model.obj" || true)"
if [ "$vertex_count" -ne "$VERTEX_COUNT" ]; then
  echo "error: expected $VERTEX_COUNT vertices, found $vertex_count" >&2
  exit 1
fi
if [ "$face_count" -ne "$TRIANGLE_COUNT" ]; then
  echo "error: expected $TRIANGLE_COUNT faces, found $face_count" >&2
  exit 1
fi

echo "Writing $OUTPUT..."
mkdir -p "$(dirname "$OUTPUT")"
{
  printf '%s\n' '// Generated by Scripts/generate-face-mesh-triangulation.sh -- do not edit.'
  printf '%s\n' '// Source: MediaPipe canonical_face_model.obj (Apache License 2.0).'
  printf '%s\n' '// https://github.com/google-ai-edge/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model.obj'
  printf '\n'
  printf '%s\n' 'public enum FaceMeshTriangulation {'
  printf '%s\n' "  public static let triangleCount = $TRIANGLE_COUNT"
  printf '%s\n' '  public static let triangles: [SIMD3<Int32>] = ['
  awk '
    /^f / {
      split($0, face, " ")
      for (i = 0; i < 3; i++) {
        split(face[i + 2], corner, "/")
        vertex[i] = corner[1] - 1
      }
      printf("    SIMD3(%d, %d, %d),\n", vertex[0], vertex[1], vertex[2])
    }
  ' "$SCRATCH/model.obj"
  printf '%s\n' '  ]'
  printf '%s\n' '}'
} > "$SCRATCH/FaceMeshTriangulation.swift"
mv "$SCRATCH/FaceMeshTriangulation.swift" "$OUTPUT"

echo "Wrote $OUTPUT ($TRIANGLE_COUNT triangles over $VERTEX_COUNT vertices)."
